### ISSUE TITLE
How to start my first project?

### ISSUE THREAD

**Issue by wugaoxue** [Christian-Nunnally/visual-drop#1]
I followed your steps. But when I put bass24.dll in Plugins. The application cannot open!!!
What shall I do?I'm in such a hurry that I can't wait to start this project.

**Comment by Christian-Nunnally** [comment]
Ah! Sorry about that. First of all, delete everything from your plugins
folder. Then the application will start again.

Second, yesterday I swapped out the bass.dll library with a new, open
source, sound library called cscore. I'll be pushing an update to the
application today or tomorrow with the new library so that you won't have
to do all of those bass.dll steps anymore. After I push the update I'll
update the installation instructions that you followed, and I'll send you a
message to let you know it's ready.

I'm excited that you're excited to get started! The whole project is in
alpha, so you might experience issues still, but I'll work with you to get
it all working.

**Comment by wugaoxue** [comment]
That's great. I'm very excited about the coming of this project.

**Comment by Christian-Nunnally** [comment]
I've posted an update! Try opening the diiagramr application to
automatically install the update. Then follow the instructions for
installing the two libraries (but skip the bass.dll part) and everything
should work.

Let me know if you have any questions.

Try playing around with the application to get the hang of it. There aren't
any tutorials yet to guide you, so good luck!

Christian Nunnally

**Comment by wugaoxue** [comment]
Thank you very much! ! !
